# NumPy

## Numpy = numerical python 
### يعني: بايثون بس مخصص للعمليات الرياضية والحسابية

In [3]:
import numpy as np  

In [4]:
my_arry = np.array([1,2,3,4,5])
print(my_arry)

[1 2 3 4 5]


* np.array() تستخدم لتحويل البيانات إلى مصفوفة

******************************************************

### Multidimensional Arrays

هي مصفوفات تحتوي على أكثر من بُعد (Dimension)، 
يعني بدل ما تكون صف واحد من الأرقام، ممكن تكون:
- صفوف وأعمدة (2D)
- أو أكتر من بعد (3D)

تُستخدم في:
- تمثيل البيانات الجدولية
- الصور (Pixels)
- تطبيقات Machine Learning

### مثال:
مصفوفة ثنائية الأبعاد (2D Array)

In [5]:
array = np.array("A") 
print(array)
print(array.ndim) # 0D → قيمة واحدة → "A"

A
0


In [6]:
array_1D = np.array([1,2,3,4,5]) 
print(array_1D)
print(array_1D.ndim) # 1D 

[1 2 3 4 5]
1


In [7]:
array_2D = np.array([[4,5,6,7,8],
                     [1,2,3,4,5]]) 
print(array_2D)
print(array_2D.ndim) # 2D 

[[4 5 6 7 8]
 [1 2 3 4 5]]
2


In [8]:
array_3D = np.array([
    [
        [4,5,6,7,8],
        [1,2,3,4,5]
    ],
    [
        [1,4,7,8,7],
        [5,2,3,6,9]
    ]
])

print(array_3D)
print(array_3D.ndim)  # 3D

[[[4 5 6 7 8]
  [1 2 3 4 5]]

 [[1 4 7 8 7]
  [5 2 3 6 9]]]
3



** 1D Array
هي مصفوفة خطية (Line) تحتوي على عناصر في صف واحد فقط.

** 2D Array
هي مصفوفة على شكل جدول (Rows & Columns).

** 3D Array
هي مجموعة من المصفوفات الثنائية الأبعاد فوق بعض (Stack of matrices).

---

** الخلاصة:
- 1D → خط
- 2D → جدول
- 3D → مجموعة جداول (مكعب بيانات)

In [9]:
print(array_3D.shape)

(2, 2, 5)


###### ما هو shape؟
هو خاصية تُستخدم لمعرفة أبعاد المصفوفة (Array Dimensions)

يعني بيقولنا:
- عدد الطبقات (Layers) 2
- عدد الصفوف (Rows)  2
- عدد الأعمدة (Columns) 5

In [10]:
print(array_3D[0][0][0]) #chain indexing  زي فهرس 
print(array_3D[1][1][4])

4
9


In [11]:
import numpy as np

array_abc = np.array([
    [
        ['a', 'b', 'c'],
        ['d', 'a', 'f'],
        ['h', 'j', 'k']
    ],
    [
        ['q', 'e', 'r'],
        ['e', 't', 'y'],
        ['u', 'i', 'o']
    ]
])

print(array_abc[0][0][2]+array_abc[0][1][1]+array_abc[1][1][1]) 

cat


# Slicing in NumPy

## ما هو Slicing؟
هو طريقة لاستخراج جزء (subset) من المصفوفة بدل ما نأخذ كل العناصر.

---

## الصيغة العامة:
array[start : end : step]

- start → بداية الاختيار
- end → نهاية الاختيار (لا يتم تضمينها)
- step → عدد الخطوات

---

## الفائدة:
- استخراج جزء من البيانات
- التعامل مع البيانات الكبيرة بسهولة

In [12]:
array_slicing = np.array([[1,2,3,4],
                         [5,6,7,8],
                         [9,10,11,12],
                         [13,14,15,16]])
print(array_slicing[0:4:2])

[[ 1  2  3  4]
 [ 9 10 11 12]]


In [13]:
array_slicing = np.array([[1,2,3,4],
                         [5,6,7,8],
                         [9,10,11,12],
                         [13,14,15,16]])
print(array_slicing[::-1])  #عكس الصفوف

[[13 14 15 16]
 [ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]


In [14]:
rray_slicing = np.array([[1,2,3,4],
                         [5,6,7,8],
                         [9,10,11,12],
                         [13,14,15,16]])
print(array_slicing[:,::-1])  

[[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]
 [16 15 14 13]]


## الفكرة:
نستخدم slicing لاستخراج أو تعديل الأعمدة داخل المصفوفة.

---

## الصيغة:
array[:, ::-1]

---

## الشرح:
- ":" → اختيار كل الصفوف
- "::-1" → عكس ترتيب الأعمدة

---

## النتيجة:
يتم عكس الأعمدة فقط مع بقاء الصفوف كما هي

In [15]:
rray_slicing = np.array([[1,2,3,4],
                         [5,6,7,8],
                         [9,10,11,12],
                         [13,14,15,16]])
print(array_slicing[:,0:4:2])  

[[ 1  3]
 [ 5  7]
 [ 9 11]
 [13 15]]


In [16]:
rray_slicing = np.array([[1,2,3,4],
                         [5,6,7,8],
                         [9,10,11,12],
                         [13,14,15,16]])
print(array_slicing[1:3,0:2])  

[[ 5  6]
 [ 9 10]]




## الفكرة:
نستخدم slicing لاستخراج جزء معين من المصفوفة (Rows & Columns).

---

## الصيغة:
array[rows, columns]

---

## في هذا المثال:
array[1:3, 0:2]

- 1:3 → اختيار الصفوف من index 1 إلى 2
- 0:2 → اختيار الأعمدة من index 0 إلى 1

---

## النتيجة:
استخراج جزء صغير من المصفوفة الأصلية

# Arithmetic Operations in NumPy

## الفكرة:
يمكن تنفيذ العمليات الحسابية على المصفوفات بسهولة وسرعة باستخدام NumPy.

---

## العمليات الأساسية:
- الجمع (+)
- الطرح (-)
- الضرب (*)
- القسمة (/)

In [17]:
arr = np.array([1, 2, 3, 4, 5])

print("Addition:", arr + 2)
print("Subtraction:", arr - 2)
print("Multiplication:", arr * 2)
print("Division:", arr / 2)

Addition: [3 4 5 6 7]
Subtraction: [-1  0  1  2  3]
Multiplication: [ 2  4  6  8 10]
Division: [0.5 1.  1.5 2.  2.5]


*****************************************

## Mathematical Functions in NumPy

## 1. sqrt
حساب الجذر التربيعي لكل عنصر في المصفوفة.

## 2. round
تقريب الأرقام لأقرب عدد صحيح أو عدد من المنازل العشرية.

## 3. floor
تقريب الرقم لأسفل (أقرب عدد صحيح أصغر).

## 4. ceil
تقريب الرقم لأعلى (أقرب عدد صحيح أكبر).

## 5. pi
ثابت π ≈ 3.14159

## 6. radii
نصف القطر (Radius) ويستخدم في حسابات الدوائر مثل المساحة أو المحيط.

----------------------------------------------------

In [18]:
arr = np.array([1.2, 2.5, 3.7, 4.9, 9])

In [19]:
print(np.sqrt(arr))

[1.09544512 1.58113883 1.92353841 2.21359436 3.        ]


In [20]:
print(np.round(arr))

[1. 2. 4. 5. 9.]


In [21]:
print(np.floor(arr))

[1. 2. 3. 4. 9.]


In [22]:
print(np.ceil(arr))

[2. 3. 4. 5. 9.]


In [23]:
print(np.pi)

3.141592653589793


In [24]:
# radii example (radius of circles)
radii = np.array([1, 2, 3, 4])
area = np.pi * radii**2
print("Circle Area:", area)

Circle Area: [ 3.14159265 12.56637061 28.27433388 50.26548246]


******************************************

# Element-wise Arithmetic in NumPy

## الفكرة:
أي عملية حسابية بين المصفوفات أو على المصفوفة يتم تطبيقها عنصر بعنصر (Element by Element).

---

## يعني إيه؟
لو عندي مصفوفتين أو مصفوفة وقيمة:
كل عنصر يتم عليه العملية لوحده.

---

## العمليات:
- جمع (+)
- طرح (-)
- ضرب (*)
- قسمة (/)

In [25]:
array_1= np.array([1,2,3,4,5])
array_2=np.array([2,7,8,9,10])


In [26]:
print("Addition:", array_1+array_2)

Addition: [ 3  9 11 13 15]


In [27]:
print("Subtraction:", array_1-array_2)

Subtraction: [-1 -5 -5 -5 -5]


In [28]:
print("Multiplication:", array_1*array_2)

Multiplication: [ 2 14 24 36 50]


In [29]:
print("Division:", array_1/array_2)

Division: [0.5        0.28571429 0.375      0.44444444 0.5       ]


In [30]:
print("Power:", array_1**array_2)

Power: [      1     128    6561  262144 9765625]


---------------------------------------------------------

# Comparison Operators in NumPy

## الفكرة:
نستخدم المقارنات لمقارنة عناصر المصفوفات أو القيم.

---

## أهم العمليات:
- أكبر من (>)
- أصغر من (<)
- يساوي (==)
- لا يساوي (!=)
- أكبر من أو يساوي (>=)
- أصغر من أو يساوي (<=)

---

## النتيجة:
كل عملية بترجع True أو False لكل عنصر (Element-wise)

In [42]:
scores = np.array([55, 70, 85, 40, 90, 60])

scores[scores <60]=0
print(scores)

# مقارنة الدرجات
print(scores > 60)   # درجات أعلى من 60
print(scores < 60)   # درجات أقل من 60
print(scores == 70)  # درجة تساوي 70
print(scores != 85)  # ليست 85
print(scores >= 80)  # درجات ممتازة
print(scores <= 60)  # درجات ضعيفة أو متوسطة

[ 0 70 85  0 90 60]
[False  True  True False  True False]
[ True False False  True False False]
[False  True False False False False]
[ True  True False  True  True  True]
[False False  True False  True False]
[ True False False  True False  True]


*******************************************

## Broadcasting

Broadcasting allows NumPy to perform operations on arrays with different shapes by virtually expanding the smaller array so that its shape matches the larger one.

This works when:
- The dimensions are equal, or
- One of the dimensions is 1

## البث (Broadcasting)

الـ Broadcasting في NumPy بيسمح بتنفيذ العمليات على مصفوفات بأحجام مختلفة عن طريق توسيع المصفوفة الأصغر بشكل افتراضي بحيث تتوافق أبعادها مع المصفوفة الأكبر.

وبيحصل ده لما:
- الأبعاد تكون متساوية، أو
- أحد الأبعاد يساوي 1

****************************************

In [43]:
array_b1 = np.array([[1, 2, 3, 4]])
array_b2 = np.array([[1], [2], [3], [4]])

In [44]:
print(array_b1.shape)
print(array_b2.shape)

(1, 4)
(4, 1)


In [46]:
print(array_b1 * array_b2)

[[ 1  2  3  4]
 [ 2  4  6  8]
 [ 3  6  9 12]
 [ 4  8 12 16]]


### Example of Broadcasting Shapes

- array_b1 shape: (1, 4) → Row vector  
- array_b2 shape: (4, 1) → Column vector  

NumPy broadcasts both arrays to shape (4, 4) before performing operations.

**************************************

## Aggregate Functions
##### summarize data and typically return asingle valus 
- **Sum (sum)**  
  بتجمع كل عناصر الـ array وتديك الناتج الكلي

- **Mean (mean)**  
  بتحسب المتوسط الحسابي للقيم (مجموع القيم ÷ عددها)

- **Standard Deviation (std)**  
  بتقيس مدى تشتت البيانات عن المتوسط

- **Variance (var)**  
  بتقيس مقدار التباين بين القيم (مربع الانحراف المعياري)

- **Median (median)**  
  القيمة اللي في النص بعد ترتيب البيانات

- **Maximum (max)**  
  أكبر قيمة في الـ array

- **Minimum (min)**  
  أصغر قيمة في الـ array

- **Index of Minimum (argmin)**  
  بيرجع رقم (index) أصغر عنصر في الـ array

- **Sum with Axis (sum(axis=...))**  
  بيجمع القيم حسب الاتجاه (صفوف أو أعمدة) بدل ما يجمع كل العناصر مرة واحدة


In [48]:
import numpy as np

arr_Aggregate = np.array([1, 2, 3, 0, 5])

print("Array:", arr_Aggregate)

# Sum
print("Sum:", np.sum(arr_Aggregate))

# Mean
print("Mean:", np.mean(arr_Aggregate))

# Standard Deviation
print("Standard Deviation:", np.std(arr_Aggregate))

# Variance
print("Variance:", np.var(arr_Aggregate))

# Median
print("Median:", np.median(arr_Aggregate))

# Max
print("Max:", np.max(arr_Aggregate))

# Min
print("Min:", np.min(arr_Aggregate))

# Argmin
print("Index of Min:", np.argmin(arr_Aggregate))

Array: [1 2 3 0 5]
Sum: 11
Mean: 2.2
Standard Deviation: 1.7204650534085253
Variance: 2.96
Median: 2.0
Max: 5
Min: 0
Index of Min: 3


In [50]:
arr_Aggregate_2D = np.array([[1, 2, 3],
                              [4, 5, 6]])

print("Array:\n", arr_Aggregate_2D)

print("Total Sum:", np.sum(arr_Aggregate_2D))
print("Sum (axis=0):", np.sum(arr_Aggregate_2D, axis=0)) # كل الاعمده جمع
print("Sum (axis=1):", np.sum(arr_Aggregate_2D, axis=1)) # جمع كل الصفوف 

Array:
 [[1 2 3]
 [4 5 6]]
Total Sum: 21
Sum (axis=0): [5 7 9]
Sum (axis=1): [ 6 15]


*****************************************

****************************

# Filtering

Filtering refers to the process of selecting elements from an array that match a given condition.

In [51]:
ages = np.array([[21,17,19,20,16,30,18,65],
                 [39,22,15,99,18,19,20,21]])

In [58]:
# Teenagers (أقل من 18)
teenagers = ages[ages < 18]
print("Teenagers:", teenagers)

# Adults (بين 18 و 65)
adults = ages[(ages > 18) & (ages < 65)]
print("Adults:", adults)

# Even numbers (الأعداد الزوجية)
evens = ages[ages % 2 == 0]
print("Evens:", evens)



Teenagers: [17 16 15]
Adults: [21 19 20 30 39 22 19 20 21]
Evens: [20 16 30 18 22 18 20]


## np.where

The np.where function is used to apply a condition on an array while keeping its original shape.

- If the condition is True → the original value is kept  
- If the condition is False → it is replaced with a given value (in this case 0)

This is useful when we want to filter data but preserve the structure of the array.

In [59]:
import numpy as np

ages = np.array([[21, 17, 19, 20],
                 [16, 30, 18, 65]])

result = np.where(ages >= 18, ages, 0)

print(result)

[[21  0 19 20]
 [ 0 30 18 65]]


******************************************

******************************************

# Random Numbers

Random numbers in NumPy are used to generate values that simulate randomness.  
They are widely used in machine learning, simulations, and data generation.

In [65]:
rng = np.random.default_rng()
print(rng.integers(1,7))

3


###### Random Number Generation

نستخدم `np.random.default_rng()` لإنشاء مولد أرقام عشوائية حديث في NumPy.

الدالة `integers(1, 7)` تقوم بتوليد رقم صحيح عشوائي بين 1 و 6 (ولا تشمل 7).

وهذا يشبه رمي حجر النرد (Dice).

*****************************

In [70]:
print(rng.integers(low=1,high=101,size=3))
print("_"*20)
print(rng.integers(low=1,high=101,size=(3,2))) #2D → جدول (Rows × Columns)

[23 26 91]
____________________
[[ 1 99]
 [15 12]
 [82 16]]


###### Random Integers with Size

الدالة `rng.integers(low=1, high=101, size=3)` تقوم بتوليد:

- أرقام من 1 (شامل)  
- إلى 100 (بدون 101)  
- عددها 3 قيم عشوائية  

وتُستخدم عندما نحتاج أكثر من قيمة عشوائية مرة واحدة.

************************************************************

In [77]:
rng = np.random.default_rng(seed=1) #- seed=1 يجعل النتيجة ثابتة كل مرة 
print(rng.integers(0, 11))

5


In [78]:
rng = np.random.default_rng(seed=1)
arr = rng.uniform(low=0, high=1, size=(3, 2))

print(arr)

[[0.51182162 0.9504637 ]
 [0.14415961 0.94864945]
 [0.31183145 0.42332645]]


## (Uniform Distribution)

دالة `uniform()` تقوم بتوليد أرقام عشوائية من توزيع منتظم.

- low = بداية المدى  
- high = نهاية المدى  
- size = شكل المصفوفة الناتجة  
- seed = يجعل النتائج ثابتة كل مرة

*************************************************

*****************************************************

In [79]:

rng = np.random.default_rng(seed=1)

# Array أساسي
array = np.array([10, 20, 30, 40, 50, 60])

print("Original array:", array)
print("_" * 30)

# Shuffle (تغيير ترتيب العناصر)
shuffled = array.copy()
rng.shuffle(shuffled)
print("Shuffled array:", shuffled)

print("_" * 30)

# Choice (اختيار عشوائي من array)
chosen = rng.choice(array, size=3)
print("Random choice:", chosen)

Original array: [10 20 30 40 50 60]
______________________________
Shuffled array: [50 10 30 20 60 40]
______________________________
Random choice: [60 20 20]


## Random Operations in NumPy

- shuffle → يعيد ترتيب عناصر المصفوفة بشكل عشوائي  
- choice → يختار عناصر عشوائية من المصفوفة  
- seed → يجعل النتائج ثابتة كل مرة